blank_issues_enabled: true
contact_links:
  - name: ğŸ”¥ åœ¨çº¿é¢„è§ˆå¿«æ·ç”³è¯·
    url: https://zoo-js.github.io/zoo-issue-helper/
    about: You can apply for online preview by clicking the link on the right.
